# This file is used by the training script in train.ipynb. You can read more about
# the format and see more examples at https://github.com/OpenAccess-AI-Collective/axolotl.
# One of the parameters you might want to play around with is `num_epochs`: if you have a
# smaller dataset size, making that large can have good results.

base_model: meta-llama/Llama-2-7b-hf
base_model_config: meta-llama/Llama-2-7b-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: true
load_in_4bit: false
strict: false

datasets:
  - path: ./data/train.jsonl
    type: alpaca_instruct.load_no_prompt
dataset_prepared_path: ./data/last_run_prepared
val_set_size: 0.05
output_dir: ./models/run1

sequence_len: 4096
sample_packing: true

adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

# This will report stats from your training run to https://wandb.ai/. If you don't want to create a wandb account you can comment this section out.
wandb_project: classify-recipes
wandb_entity:
wandb_watch:
wandb_run_id: run1
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 5
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 20
save_steps: 60
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"