[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:pydantic.*:",
    "ignore::UserWarning:pydantic.*:",
    "ignore::DeprecationWarning:litellm.*:",
    "ignore::UserWarning:litellm.*:"
]