fpb:

  model_name: "your_model_name"

  max_tokens: 128

  temperature: 0.7

  top_p: 0.7

  top_k: 50

  repetition_penalty: 1.1

prompt_template: "Your prompt template here"
  data_directory: "data"
  seeds: [42, 123, 456]

