# CI Configuration for GitHub Actions
# This configuration uses mock models and avoids external dependencies

# Mock model for CI testing - no actual API calls
model: "mock/ci-test-model"

# No API base for CI - all calls will be mocked
api_base: null

# Default tasks for CI testing
tasks:
  - fomc
  - fpb

# Generation parameters optimized for CI
max_tokens: 50
temperature: 0.0
top_p: 0.9
top_k: null
repetition_penalty: 1.0

# Small batch size for faster CI runs
batch_size: 10
prompt_format: zero_shot

# Quick timeout for CI
timeout: 30

# CI-specific settings
ci_mode: true
skip_api_calls: true

# Logging configuration for CI
logging:
  level: "INFO"
  console:
    enabled: true
    level: "INFO"
  file:
    enabled: false  # Don't create log files in CI
  components:
    litellm: "ERROR"  # Suppress LiteLLM logs in CI
    batch_utils: "WARNING"
    inference: "INFO"
    evaluation: "INFO"