model: "together_ai/meta-llama/Llama-4-Scout-17B-16E-Instruct"
tasks:
  - fomc
  - fpb
max_tokens: 128
temperature: 0.7
top_p: 0.9
top_k: null
repetition_penalty: 1.0
batch_size: 1
sample_size: 10
prompt_format: zero_shot