name: Run Tests in Groups

# This workflow runs tests in separate groups to avoid test isolation issues
# Module tests that dynamically import code are run separately from other tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: |
        pip install uv
        
    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt
        uv pip install -e .
        
    - name: Run Unit Tests
      run: |
        echo "Running unit tests..."
        uv run pytest tests/unit/ -v
        
    - name: Run Prompt Tests
      run: |
        echo "Running prompt tests..."
        uv run pytest tests/prompts/ -v
        
    - name: Run Multi-Task Tests
      run: |
        echo "Running multi-task tests..."
        uv run pytest tests/multi_task/ -v
        
    - name: Run Integration Tests
      run: |
        echo "Running integration tests..."
        uv run pytest tests/integration/ -v
        
    - name: Run Module Tests - Inference
      run: |
        echo "Running module inference tests..."
        uv run pytest tests/modules/test_all_inference.py -v
        
    - name: Run Module Tests - Evaluation
      run: |
        echo "Running module evaluation tests..."
        uv run pytest tests/modules/test_all_evaluation.py -v